name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Tests
        run: cargo test
      - name: Lints
        run: cargo clippy -- -D warnings