[package]
name = "guessing-game-grader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
colored = "2.1.0"
prettydiff = { version = "0.7.0", default-features = false }
textwrap = "0.16.1"
